# Generated by Django 4.2.17 on 2025-02-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
