# Generated by Django 4.2.17 on 2025-02-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userprofile_address_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
